import type { OmRequirements } from './validateRequirements'

const SAFE_SLUG = /^[a-z0-9][a-z0-9-]*$/

/**
 * Zamienia zwalidowane wymagania w plik markdown, który skill
 * `om-mockup-prototype` czyta w swoim kroku 1. Czysta funkcja: string
 * wchodzi, string wychodzi, zero I/O.
 *
 * Nagłówki `## User stories` i `## Screen inventory` są celowo dosłowne -
 * skill szuka historii z kryteriami akceptacji i inwentarza ekranów, a
 * człowiek po stronie Open Mercato musi je znaleźć w pół sekundy.
 */
export function renderRequirementsMarkdown(req: OmRequirements, company: { name: string }): string {
  const lines: string[] = []

  lines.push(`# ${company.name} - Open Mercato backend requirements`, '')
  lines.push(req.summary, '')
  lines.push(
    '> Generated by mercatify-labs `om_prototyper`. Every sample value is fictional.',
    '> Nothing here decides business policy; open questions below are unresolved.',
    '',
  )

  lines.push('## Epics', '')
  for (const epic of req.epics) {
    lines.push(`### ${epic.id} - ${epic.title}`, '', epic.outcome, '')
  }

  lines.push('## User stories', '')
  for (const story of req.stories) {
    lines.push(`### ${story.id} (${story.epicId})`, '')
    lines.push(`As a ${story.role}, I want to ${story.goal}, so that ${story.outcome}.`, '')
    lines.push('Acceptance criteria:', '')
    for (const criterion of story.acceptanceCriteria) lines.push(`- ${criterion}`)
    lines.push('')
  }

  lines.push('## Screen inventory', '')
  lines.push('| Screen | Archetype | States | Stories | Sections |', '|---|---|---|---|---|')
  for (const screen of req.screens) {
    lines.push(
      `| ${screen.id} ${screen.name} | ${screen.archetype} | ${screen.states.join(', ')} | ` +
        `${screen.storyIds.join(', ')} | ${screen.sectionRefs.join(', ')} |`,
    )
  }
  lines.push('')

  lines.push('## Open questions', '')
  if (req.openQuestions.length === 0) {
    lines.push('None recorded.', '')
  } else {
    for (const question of req.openQuestions) lines.push(`- ${question}`)
    lines.push('')
  }

  return lines.join('\n')
}

/**
 * Dokładna komenda ze skilla (jego krok 3). Uruchamiana w checkoutcie Open
 * Mercato, nigdy tutaj - ten pakiet nie ma i nie będzie miał zależności od
 * Open Mercato (SPEC.md §1).
 */
export function handoffCommand(slug: string, requirementsPath: string): string {
  if (!SAFE_SLUG.test(slug)) {
    throw new Error(`[mercatify-labs] Unsafe prototype slug: ${slug} (expected ^[a-z0-9][a-z0-9-]*$)`)
  }
  return (
    'node .ai/skills/om-mockup-prototype/scripts/init-mockup.mjs ' +
    `"${slug}" --requirements "${requirementsPath}"`
  )
}
